#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_create:
  path: /user/create
  controller: App\User\Infrastructure\Controller\CreateUserController
  methods: [ POST ]

user_login:
  path: /user/login
  controller: App\User\Infrastructure\Controller\LoginUserController
  methods: [ POST ]

book_create:
  path: /book/create
  controller: App\Book\Infrastructure\Controller\CreateBookController
  methods: [ POST ]
